services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ecom-db'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=root'
    ports:
      - '5432'
    volumes:
      - './volumes/postgres:/var/lib/postgresql/data'
